-- Generates the palette exports for programs that cannot read a lush theme.
--
--   nvim --headless -l export.lua
--
-- Everything here is derived from colors/akira.lua, so the generated files are
-- outputs: edit the theme, re-run this, never hand-edit what it writes.

vim.opt.rtp:prepend(vim.fn.stdpath("data") .. "/lazy/lush.nvim")

local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h")
vim.opt.rtp:prepend(root)
vim.cmd.colorscheme("akira")

local function hex(group, key)
    local hl = vim.api.nvim_get_hl(0, { name = group, link = false })
    assert(hl[key], group .. "." .. key .. " is unset")
    return string.format("#%06x", hl[key])
end

local bg, fg = hex("Normal", "bg"), hex("Normal", "fg")

local function write(path, body)
    local full = root .. "/" .. path
    vim.fn.mkdir(vim.fn.fnamemodify(full, ":h"), "p")
    local f = assert(io.open(full, "w"))
    f:write(body)
    f:close()
    print("wrote " .. path)
end

local ghostty = {
    "# Generated by export.lua -- do not edit by hand.",
    "background = " .. bg,
    "foreground = " .. fg,
    "cursor-color = " .. hex("Cursor", "bg"),
    "cursor-text = " .. hex("Cursor", "fg"),
    "selection-background = " .. hex("Visual", "bg"),
    "selection-foreground = " .. hex("Visual", "fg"),
    "",
}
for i = 0, 15 do
    local c = vim.g["terminal_color_" .. i]
    assert(c, "terminal_color_" .. i .. " is unset")
    table.insert(ghostty, string.format("palette = %d=%s", i, c))
end
write("ghostty/akira", table.concat(ghostty, "\n") .. "\n")

local function slot(i)
    local c = vim.g["terminal_color_" .. i]
    assert(c, "terminal_color_" .. i .. " is unset")
    return c:lower()
end

-- Only the client.* colours can be delivered this way. i3 scopes variables per
-- file: a parent's variables reach an included file, but a `set` here never
-- escapes back out, and `include` is rejected inside a bar block. The bar
-- therefore reads the palette from the X resource database below instead.
local i3 = {
    "# Generated by export.lua -- do not edit by hand.",
    "set $akira_bg " .. bg,
    "set $akira_fg " .. fg,
    "set $akira_white " .. slot(15),
    "set $akira_red " .. slot(1),
    "",
    "# border backgr. text indicator child_border",
    "client.focused          $akira_fg $akira_fg $akira_fg $akira_fg",
    "client.unfocused        $akira_fg $akira_bg $akira_bg $akira_bg $akira_fg",
    "client.focused_inactive $akira_fg $akira_fg $akira_fg $akira_fg $akira_fg",
    "client.urgent           $akira_fg $akira_fg $akira_fg $akira_fg $akira_fg",
    "client.placeholder      $akira_fg $akira_fg $akira_fg $akira_fg $akira_fg",
    "client.background       $akira_fg",
}
write("i3/colors.conf", table.concat(i3, "\n") .. "\n")

-- Merged by ~/.xinitrc before i3 starts, so the bar block can pull these in
-- with set_from_resource from the top-level config's own scope.
local xresources = {
    "! Generated by export.lua -- do not edit by hand.",
    "akira.bg:    " .. bg,
    "akira.fg:    " .. fg,
    "akira.white: " .. slot(15),
    "akira.red:   " .. slot(1),
}
write("i3/akira.Xresources", table.concat(xresources, "\n") .. "\n")

-- bumblebee-status cycles module backgrounds through this list, all on the
-- theme background, so the order is just the wires in a readable rotation.
local cycle = { 6, 1, 2, 3, 7 }
local pairs_out = {}
for _, i in ipairs(cycle) do
    table.insert(pairs_out, string.format('\t\t{"fg": "%s", "bg": "%s"}', bg, slot(i)))
end
local bumblebee = {
    "{",
    '\t"_comment": "Generated by export.lua -- do not edit by hand.",',
    '\t"icons": [ "awesome-fonts" ],',
    '\t"defaults": {',
    '\t\t"separator-block-width": 0',
    "\t},",
    '\t"cycle": [',
    table.concat(pairs_out, ",\n"),
    "\t]",
    "}",
}
write("bumblebee/akira.json", table.concat(bumblebee, "\n") .. "\n")
