-- Generates the palette exports for programs that cannot read a lush theme.
--
--   nvim --headless -l export.lua
--
-- Everything here is derived from colors/akira.lua, so the generated files are
-- outputs: edit the theme, re-run this, never hand-edit what it writes.

vim.opt.rtp:prepend(vim.fn.stdpath("data") .. "/lazy/lush.nvim")

local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h")
vim.opt.rtp:prepend(root)
vim.cmd.colorscheme("akira")

local function hex(group, key)
    local hl = vim.api.nvim_get_hl(0, { name = group, link = false })
    assert(hl[key], group .. "." .. key .. " is unset")
    return string.format("#%06x", hl[key])
end

local bg, fg = hex("Normal", "bg"), hex("Normal", "fg")

local function write(path, body)
    local full = root .. "/" .. path
    vim.fn.mkdir(vim.fn.fnamemodify(full, ":h"), "p")
    local f = assert(io.open(full, "w"))
    f:write(body)
    f:close()
    print("wrote " .. path)
end

local ghostty = {
    "# Generated by export.lua -- do not edit by hand.",
    "background = " .. bg,
    "foreground = " .. fg,
    "cursor-color = " .. hex("Cursor", "bg"),
    "cursor-text = " .. hex("Cursor", "fg"),
    "selection-background = " .. hex("Visual", "bg"),
    "selection-foreground = " .. hex("Visual", "fg"),
    "",
}
for i = 0, 15 do
    local c = vim.g["terminal_color_" .. i]
    assert(c, "terminal_color_" .. i .. " is unset")
    table.insert(ghostty, string.format("palette = %d=%s", i, c))
end
write("ghostty/akira", table.concat(ghostty, "\n") .. "\n")
